// <auto-generated />
namespace SportStore.API.Migration.Token
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbInitializer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInitializer));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201750224_DbInitializer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
